name: Test using Gradle

on: 
    push:
    pull_request:
        branches:
          - develop

jobs:
    Gradle-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
            - name: Clean build
              run: ./gradlew clean build
