name: Linux env
on:
    push:
    pull_request:
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: joschi/setup-jdk@v2.3.0
              with:
                java-version: 21
            - name: Build
              run: ./gradlew build